configurations/urls.py
from django.contrib import admin

from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include("products.urls", namespace="products")),
    path("categories/", include("categories.urls", namespace="categories")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # path('users/', UserList.as_view()),
    # path('users/<pk>/', UserDetails.as_view()),
    # path('groups/', GroupList.as_view()),
]

products/urls.py
from django.urls import include, path
from rest_framework import routers
from products import views
from products.views import (
    ProductViewSet,
    ProductCreate,
    ProductDelete,
    ProductUpdate,
    ProductList,
    ProductDetail,
)


router = routers.DefaultRouter()
router.register(r"product-api", ProductViewSet)

app_name = "products"

urlpatterns = [
    path("", include(router.urls,)),
    path("product/add/", ProductCreate.as_view(), name="product-add"),
    path("product/<int:pk>/", ProductDetail.as_view(), name="product-detail"),
    path("product/<int:pk>/update/", ProductUpdate.as_view(), name="product-update"),
    path("product/<int:pk>/delete/", ProductDelete.as_view(), name="product-delete"),
    path("product/", ProductList.as_view(), name="product-list"),
]

products/models.py
from django.db import models
from categories.models import Category
from django.urls import reverse
from django.template.defaultfilters import slugify

# Create your models here.


class Product(models.Model):
    """
    Product Model class
    """

    class Meta:
        ordering = ("-created",)
        verbose_name = "Product"
        verbose_name_plural = "Products"

    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    name = models.CharField(max_length=200, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("products:product-detail", kwargs={"pk": self.slug})

products/forms.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    name = models.CharField(max_length=200)

products/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from products.models import Product

from django.shortcuts import render

import datetime
from rest_framework import viewsets
import json
from rest_framework.exceptions import NotFound
from products.models import Product
from rest_framework import permissions
from rest_framework.exceptions import APIException

from rest_framework.response import Response
from django.core import serializers
from products.serializers import ProductSerializer
from django.contrib.auth.mixins import LoginRequiredMixin
from django_filters.rest_framework import DjangoFilterBackend

# Create your views here.
class ProductViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """

    queryset = Product.objects.all().order_by("-created")
    serializer_class = ProductSerializer
    # filter_backends = [django_filters.rest_framework.DjangoFilterBackend]
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["name"]

    def create(self, request):
        today = datetime.date.today()
        todays_records = Product.objects.filter(created__gt=today)[:10]
        if todays_records.count() > 10:
            raise APIException("today limit reached")
        data = request.data.copy()
        serializer = ProductSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors)

    def partial_update(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.serializer_class(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)

        today = datetime.date.today()

        todays_records = Product.objects.filter(updated_at__gt=today)[:10]
        if todays_records.count() > 10:
            raise APIException("today limit reached")

        serializer.save()
        return Response(serializer.data)


class ProductCreate(CreateView):

    # class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    fields = ["name","price","quantity","category"]

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProductUpdate(UpdateView):
    model = Product
    # fields = ["name"]
    fields = ["name","price","quantity","category"]


class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy("products:product-list")


class ProductList(ListView):
    model = Product


class ProductDetail(DetailView):
    model = Product

    # def get_object(self):
    # obj = super().get_object()
    # Record the last accessed date
    # obj.last_accessed = timezone.now()
    # obj.save()
    # return obj

templates/products/product_confirm_delete.html
{% extends "base.html" %}

{% block title %} 
{{ object.name }} are you sure you want to delete

{% endblock %}

{% block content %}


<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
<a href="{% url  'products:product-list' %}">cancel and go to list </a>



{% endblock %}

templates/products/product_detail.html
{% extends "base.html" %}

{% block title %}
{{ object.name }} details

{% endblock %}

{% block content %}
<h2>{{ object.name }}</h2>


<p>{{ object.price }}</p>
<p>created: {{ object.created|date }}</p>
<a href="{% url  'products:product-list' %}">go to list </a>

{% endblock %}

templates/products/product_form.html
{% extends "base.html" %}

{% block title %} 


{{ object.name }} add/update

{% endblock %}


{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
<a href="{% url  'products:product-list' %}">cancel and go to list </a>

{% endblock %}

templates/products/product_list.html
{% extends "base.html" %}
{% block title %}
product list 
{% endblock %}


{% block content %}
<h2>Product</h2>
<ul>
    {% for product in object_list %}
    <li>

        <a href="{% url  'products:product-detail' product.id %}">{{ product.name }} </a>
        <a href="{% url  'products:product-update' product.id %}"> edit </a>
        <a href="{% url  'products:product-delete' product.id %}">delete </a>
        
    </li>

    {% endfor %}
</ul>
<a href="{% url  'products:product-add' %}">Add </a>
{% endblock %}