categories/urls.py
from django.urls import include, path
from rest_framework import routers
from categories import views


from categories.views import (
    CategoryViewSet,
    CategoryCreate,
    CategoryDelete,
    CategoryUpdate,
    CategoryList,
    CategoryDetail,
)


router = routers.DefaultRouter()
router.register(r"categories-api", CategoryViewSet)

app_name = "categories"
urlpatterns = [
    path("", include(router.urls,)),
    path("category/add/", CategoryCreate.as_view(), name="category-add"),
    path("category/<int:pk>/", CategoryDetail.as_view(), name="category-detail"),
    path("category/<int:pk>/update/", CategoryUpdate.as_view(), name="category-update"),
    path("category/<int:pk>/delete/", CategoryDelete.as_view(), name="category-delete"),
    path("category/", CategoryList.as_view(), name="category-list"),
]

configurations/urls.py
from django.contrib import admin

from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("products/", include("products.urls", namespace="products")),
    path("categories/", include("categories.urls", namespace="categories")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # path('users/', UserList.as_view()),
    # path('users/<pk>/', UserDetails.as_view()),
    # path('groups/', GroupList.as_view()),
]

products/urls.py
from django.urls import include, path
from rest_framework import routers
from products import views
from products.views import (
    ProductViewSet,
    ProductCreate,
    ProductDelete,
    ProductUpdate,
    ProductList,
    ProductDetail,
)


router = routers.DefaultRouter()
router.register(r"product-api", ProductViewSet)

app_name = "products"

urlpatterns = [
    path("", include(router.urls,)),
    path("product/add/", ProductCreate.as_view(), name="product-add"),
    path("product/<int:pk>/", ProductDetail.as_view(), name="product-detail"),
    path("product/<int:pk>/update/", ProductUpdate.as_view(), name="product-update"),
    path("product/<int:pk>/delete/", ProductDelete.as_view(), name="product-delete"),
    path("product/", ProductList.as_view(), name="product-list"),
]

categories/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.utils.translation import gettext as _
from categories.managers import CommentManager

# Create your models here.


class Category(models.Model):
    objects = CommentManager()
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    created = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    parent = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name=_("Parent Category"),
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("categories:category-detail", kwargs={"pk": self.id})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def children(self):
        """Return replies of a Category."""
        return Category.objects.filter(parent=self)

    @property
    def is_parent(self):
        """Return `True` if instance is a parent."""
        if self.parent is not None:
            return False
        return True

categories/views.py
from django.shortcuts import render
from django_filters.rest_framework import DjangoFilterBackend
from django.urls import reverse_lazy

from rest_framework.response import Response
import datetime
from rest_framework import viewsets
import json
from categories.models import Category
from rest_framework import permissions
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView

from rest_framework.exceptions import APIException

from django.core import serializers
from categories.serializers import CategorySerializer


# Create your views here.
class CategoryViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """

    queryset = Category.objects.all().order_by("-created")
    serializer_class = CategorySerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ["name"]

    def partial_update(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.serializer_class(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)

        today = datetime.date.today()

        todays_records = Category.objects.filter(updated_at__gt=today)[:10]
        if todays_records.count() > 10:
            raise APIException("today limit reached")

        serializer.save()
        return Response(serializer.data)





class CategoryCreate(CreateView):

    # class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    fields = ["name","parent"]

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class CategoryUpdate(UpdateView):
    model = Category
    queryset = Category.objects.filter()

    # fields = ["name"]
    fields = ["name","parent"]


class CategoryDelete(DeleteView):
    model = Category
    queryset = Category.objects.filter()

    success_url = reverse_lazy("products:product-list")


class CategoryList(ListView):
    # import pdb; pdb.set_trace()
    model = Category
    queryset = Category.objects.filter()


class CategoryDetail(DetailView):
    model = Category

    # def get_object(self):
    # obj = super().get_object()
    # Record the last accessed date
    # obj.last_accessed = timezone.now()
    # obj.save()
    # return obj

templates/categories/category_confirm_delete.html
{% extends "base.html" %}

{% block title %} 
{{ object.name }} are you sure you want to delete

{% endblock %}

{% block content %}


<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
<a href="{% url  'categories:category-list' %}">cancel and go to list </a>



{% endblock %}

templates/categories/category_detail.html
{% extends "base.html" %}

{% block title %}
{{ object.name }} details

{% endblock %}

{% block content %}
<h2>{{ object.name }}</h2>


<p>{{ object.price }}</p>
<p>created: {{ object.created|date }}</p>
<a href="{% url  'categories:category-list' %}">go to list </a>

{% endblock %}

templates/categories/category_form.html
{% extends "base.html" %}

{% block title %} 


{{ object.name }} add/update

{% endblock %}


{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
<a href="{% url  'categories:category-list' %}">cancel and go to list </a>

{% endblock %}

templates/categories/category_list.html
{% extends "base.html" %}
{% block title %}
categories list
{% endblock %}


{% block content %}
<h2>category</h2>


<a href="{% url  'categories:category-add' %}">Add </a>




<ul>
    {% for comment in object_list %}
    <li>


        <a href="{% url  'categories:category-detail' comment.id %}">{{ comment.name }} </a>
        <a href="{% url  'categories:category-update' comment.id %}"> edit </a>
        <a href="{% url  'categories:category-delete' comment.id %}">delete </a>


        <ul>

            {% for reply in comment.children %}
            <li>


                <a href="{% url  'categories:category-detail' reply.id %}">{{ reply.name }} </a>
                <a href="{% url  'categories:category-update' reply.id %}"> edit </a>
                <a href="{% url  'categories:category-delete' reply.id %}">delete </a>


                <ul>
                    {% for r in reply.children %}


                    <li>

                        <a href="{% url  'categories:category-detail' r.id %}">{{ r.name }} </a>
                        <a href="{% url  'categories:category-update' r.id %}"> edit </a>
                        <a href="{% url  'categories:category-delete' r.id %}">delete </a>



                    </li>
                    {% endfor %}

                </ul>
            </li>
            {% endfor %}
        </ul>

    </li>
    {% endfor %}
</ul>








{% endblock %}